export default {
  FD_p01_FH_31_240716: {
    "MUC16 mut": "",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p01_FH_57_372440: {
    "MUC16 mut": "",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p01_MC_13136_42571_C1: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p01_MC_7053_39955_B1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p01_MC_7301_40353_A3: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p01_MC_8228_41080_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p01_UA_CU-23_S-15-0033313_B1": {
    "MUC16 mut": "",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p01_UA_CU-42_S-11-0002981_E3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p02_FH_11_208877: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p02_FH_28_231865; 230368": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p02_FH_52_319488: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p02_FH_76_493391: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p02_MC_4086_39149_C6: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p02_MC_4787_37440_A1: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p02_MC_7598_40885_B1: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p02_UA_CU-12_S-14-0007480_A6": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p03_FH_14_210413: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "2.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p03_FH_33_244726; 246014": {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p03_FH_34_260388: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p03_FH_56_360612: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p03_FH_65_465021; 465023": {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p03_FH_95_631766: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p03_MC_2710_37852_F3: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p03_UA_CU-35_S-14-0030753_E1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p04_FH_19_215376: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p04_FH_22_218317; 218726": {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p04_FH_96_206843: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p04_MC_2313_37530_B9: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p04_UA_CU-15_S-13-0034287_A2": {
    "MUC16 mut": "",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p04_UA_CU-25_S-11-0010626_B3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p04_UA_CU-30_S-10-0035607_A4": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p04_UA_CU-45_S-11-0025953_B7": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p05_FH_2_205927: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p05_FH_84_533557: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p05_MC_2398_37572_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p05_MC_3714_38616_A1: {
    "MUC16 mut": "",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p05_MC_4378_39433_A4: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p05_MC_4564_41946_A1: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p05_MC_7270_40298_K1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p05_UA_CU-17_S-13-0008240_A1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p06_FH_44_277998: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p06_FH_85_555178; 555177": {
    "MUC16 mut": "",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p06_FH_94_654490: {
    "MUC16 mut": "",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p06_MC_1711_36173_D1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p06_MC_3845_38791_A1: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p06_MC_8986_36754_C4: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p06_UA_CU-01_S-07-0009498_A10": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p06_UA_CU-31_S-07-0032072_A8": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p07_FH_15_210039: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "2.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p07_FH_5_500475: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p07_FH_83_517774: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p07_MC_5462_38435_B1: {
    "MUC16 mut": "",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p07_MC_7715_41079_A6: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p07_UA_CU-11_S-13-0022284_A4": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p07_UA_CU-19_S-17-0024563_A14": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p07_UA_CU-39_S-11-0009142_B2": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p08_FH_48_297929: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p08_FH_86_535474: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p08_FH_90_555596: {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p08_MC_13280_42695_C3: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "2.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p08_MC_3604_38471_A2: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p08_UA_CU-21_S-17-0012504_C1": {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p08_UA_CU-22_S-15-0030998_A1": {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p08_UA_CU-36_S-12-0032630_B14": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p09_FH_41_277568: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p09_FH_72_476540: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p09_FH_78_527499: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p09_FH_81_525976; 525977": {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p09_MC_2054_36978_C2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p09_UA_CU-06_S-07-0023499_A2": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p09_UA_CU-08_S-07-0027436_B6": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p10_FH_25_222844; 222854": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "2.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p10_FH_6_500550: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p10_FH_8_501213: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p10_MC_2510_37571_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p10_MC_5161_41634_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p10_MC_7924_41550_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p10_UA_CU-43_S-14-0024532_A2": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p11_FH_36_265490; 265491": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p11_FH_39_271005: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p11_FH_77_487495: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p11_MC_4237_39352_B1: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p11_MC_8005_39918_C2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p11_UA_CU-04_S-10-0000363_C1": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p11_UA_CU-09_S-11-0017293_B1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p11_UA_CU-46_S-12-0007994_B6": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p12_FH_3_500395: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p12_FH_97_352244: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p12_MC_2553_37712_C1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p12_MC_8318_41218_C3: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p12_UA_CU-20_S-15-0035461_B3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p12_UA_CU-26_S-09-0003181_A5": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p12_UA_CU-40_S-14-0005518_B2": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p13_FH_35_262427: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p13_FH_93_555588: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p13_MC_13129_42569_E1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p13_MC_2121_36517_G2: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p13_MC_5980_39738_D2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p13_UA_CU-27_S-09-0000175_C3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p13_UA_CU-34_S-13-0008803_J1": {
    "MUC16 mut": "",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p13_UA_CU-38_S-13-0021879_A8": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p14_FH_49_296927: {
    "MUC16 mut": "",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p14_FH_53_350407: {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p14_MC_2303_37504_B1: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p14_MC_7064_39968_D7: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p14_UA_CU-03_S-08-0007631_A2": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p14_UA_CU-29_S-07-0001549_A3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p14_UA_CU-37_S-11-0020094_A3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p15_FH_29_232982: {
    "MUC16 mut": "",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p15_FH_38_265871: {
    "MUC16 mut": "",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p15_FH_4_206053: {
    "MUC16 mut": "",
    "Protein cluster": "1.0",
    "Tumor Grade": "2.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p15_MC_7078_39996_A2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p15_MC_8985_42454_F2: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p15_UA_CU-02_S-13-0021202_A5": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p15_UA_CU-05_S-07-0019837_B1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p15_UA_CU-07_S-08-0003179_A1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p16_FH_10_500869: {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p16_FH_12_501301: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p16_FH_17_212713: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p16_FH_82_517758: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p16_MC_3219_41837_C2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p16_MC_3812_38735_A6: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p16_UA_CU-24_S-07-0006305_A1": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p17_FH_70_494830; 494829": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p17_FH_7_206382; 206375": {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p17_MC_4421_39549_D1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p17_MC_4968_37624_B1: {
    "MUC16 mut": "",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p17_UA_CU-16_S-15-0016317_B7": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  "FD_p17_UA_CU-28_S-07-0021920_B3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p17_UA_CU-41_S-11-0016358_A3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p18_FH_1_500263: {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p18_FH_69_536848; 533117": {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p18_MC_2807_37917_D6: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p18_MC_4050_39099_A2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  FD_p18_MC_4350_38999_B2: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  FD_p18_MC_4541_41911_C6: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p18_UA_CU-10_S-14-0022078_C1": {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p19_FH_71_474534; 474536": {
    "MUC16 mut": "0.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p19_FH_79_503836; 503834": {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p19_FH_99_418442; 418441": {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p19_MC_4114_39184_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p19_UA_CU-13_S-13-0006146_C3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p19_UA_CU-14_S-13-0003847_B3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p19_UA_CU-44_S-12-0006563_D3": {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p20_FH_26_223154; 222912": {
    "MUC16 mut": "0.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  "FD_p20_FH_55_351913; 352452": {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p20_FH_80_476423: {
    "MUC16 mut": "1.0",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p20_FH_91_555175: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p20_MC_2685_37845_B1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p20_MC_7339_40414_A1: {
    "MUC16 mut": "0.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  "FD_p20_UA_CU-32_S-13-0010181_B3": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p21_FH_20_218201: {
    "MUC16 mut": "",
    "Protein cluster": "4.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p21_FH_27_228608: {
    "MUC16 mut": "",
    "Protein cluster": "5.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "",
  },
  FD_p21_MC_3480_38147_A2: {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "PRO",
  },
  FD_p21_MC_4322_38538_C14: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
  FD_p21_MC_7203_40170_B2: {
    "MUC16 mut": "1.0",
    "Protein cluster": "3.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "other",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "DIF",
  },
  "FD_p21_UA_CU-18_S-14-0036688_B4": {
    "MUC16 mut": "1.0",
    "Protein cluster": "1.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OM",
    "Tumor response": "refractory",
    "TCGA-RNA clusters (VerHaak)": "IMR",
  },
  "FD_p21_UA_CU-33_S-14-0021444_B4": {
    "MUC16 mut": "1.0",
    "Protein cluster": "2.0",
    "Tumor Grade": "3.0",
    "Tumor Location Group": "OV",
    "Tumor response": "sensitive",
    "TCGA-RNA clusters (VerHaak)": "MES",
  },
};
